# Generated by Django 5.2.17 on 2026-08-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="單價（試算當下的真實數字）",
                        max_digits=12,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=10)),
                (
                    "ai_summary_text",
                    models.TextField(
                        blank=True,
                        help_text="LLM 生成摘要；複核核准後改存系統制式文字",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "pending_verification"),
                            ("pending_review", "pending_review"),
                            ("pending_approval", "pending_approval"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                (
                    "price_deviation_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="本次單價與該供應商+產品歷史已核准均價的偏離百分比；null＝過去無已核准紀錄可比較",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="erp.product",
                    ),
                ),
                (
                    "source_suggestion",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_suggestion_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="erp.purchasesuggestion",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="crm.supplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_column="approver_id",
                        help_text="實際認領/決議的使用者；認領前為 null",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_approvals",
                        to="core.user",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="core.role",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        db_column="quote_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="procurement.quote",
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
            },
        ),
    ]
