# Generated by Django 5.2.17 on 2026-08-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refresh_session'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('quote',), name='approvals_quote_unique'),
        ),
    ]
