# Generated by Django 5.2.17 on 2026-08-28 12:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('crm', '0002_supplier_code_supplier_contact_supplier_is_active_and_more'),
        ('erp', '0002_productcategory_product_description_and_more'),
        ('procurement', '0003_backfill_pending_approvals'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS "btree_gist";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='核准政策名稱', max_length=100)),
                ('currency', models.CharField(db_comment='ISO 4217 三碼大寫幣別', max_length=3)),
                ('min_amount', models.DecimalField(db_comment='適用最低金額（含）', decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, db_comment='適用最高金額（不含）；NULL 表示無上限', decimal_places=2, max_digits=14, null=True)),
                ('active_from', models.DateTimeField(db_comment='政策生效時間')),
                ('active_until', models.DateTimeField(blank=True, db_comment='政策失效時間；NULL 表示持續有效', null=True)),
                ('is_active', models.BooleanField(db_comment='是否允許新案件選用', default=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'approval_policies',
                'db_table_comment': '版本化金額核准政策',
                'indexes': [models.Index(fields=['currency', 'is_active', 'active_from'], name='approval_policy_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='approval_policy_min_nonnegative'), models.CheckConstraint(condition=models.Q(('max_amount__isnull', True), ('max_amount__gt', models.F('min_amount')), _connector='OR'), name='approval_policy_amount_range'), models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gt', models.F('active_from')), _connector='OR'), name='approval_policy_active_period')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, db_comment='供應商自己的品項代碼', max_length=100)),
                ('lead_time_days', models.PositiveIntegerField(db_comment='預設交期天數', default=0)),
                ('minimum_order_quantity', models.DecimalField(db_comment='最小訂購量', decimal_places=3, default=1, max_digits=14)),
                ('quality_status', models.CharField(choices=[('qualified', 'qualified'), ('conditional', 'conditional'), ('blocked', 'blocked')], db_comment='品質資格：qualified/conditional/blocked', default='qualified', max_length=20)),
                ('is_active', models.BooleanField(db_comment='是否允許用於新 RFQ', default=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
                ('product', models.ForeignKey(db_column='product_id', db_comment='對應 products.id', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='erp.product')),
                ('supplier', models.ForeignKey(db_column='supplier_id', db_comment='對應 suppliers.id', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='crm.supplier')),
            ],
            options={
                'db_table': 'supplier_products',
                'db_table_comment': '供應商與可供應品項的主檔關係',
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(db_comment='未稅單價', decimal_places=2, max_digits=14)),
                ('currency', models.CharField(db_comment='ISO 4217 三碼大寫幣別', default='TWD', max_length=3)),
                ('minimum_quantity', models.DecimalField(db_comment='此價格級距的最小數量', decimal_places=3, default=1, max_digits=14)),
                ('valid_from', models.DateTimeField(db_comment='價格生效時間')),
                ('valid_until', models.DateTimeField(blank=True, db_comment='價格失效時間；NULL 表示持續有效', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('created_by', models.ForeignKey(db_column='created_by_id', db_comment='建立價格版本的 users.id', on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_prices', to='core.user')),
                ('supplier_product', models.ForeignKey(db_column='supplier_product_id', db_comment='對應 supplier_products.id', on_delete=django.db.models.deletion.PROTECT, related_name='price_versions', to='procurement.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_price_versions',
                'db_table_comment': '供應商品項價格版本；正式交易另存快照',
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_comment='政策內的核准順序，從 1 開始')),
                ('decision_mode', models.CharField(choices=[('any_one', 'any_one'), ('all', 'all')], db_comment='同一步驟決議方式：any_one/all', default='any_one', max_length=10)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('policy', models.ForeignKey(db_column='policy_id', db_comment='對應 approval_policies.id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procurement.approvalpolicy')),
                ('role', models.ForeignKey(db_column='role_id', db_comment='此步驟可決議的 roles.id', on_delete=django.db.models.deletion.PROTECT, related_name='approval_policy_steps', to='core.role')),
            ],
            options={
                'db_table': 'approval_policy_steps',
                'db_table_comment': '核准政策的角色與順序快照來源',
                'constraints': [models.UniqueConstraint(fields=('policy', 'sequence'), name='approval_policy_steps_sequence_unique'), models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='approval_policy_steps_sequence_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='supplier_products_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_quantity__gt', 0)), name='supplier_products_moq_positive'),
        ),
        migrations.AddIndex(
            model_name='supplierpriceversion',
            index=models.Index(fields=['supplier_product', 'currency', 'valid_from'], name='supplier_price_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceversion',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='supplier_prices_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceversion',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gt', 0)), name='supplier_prices_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpriceversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='supplier_prices_valid_period'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE approval_policies
                    ADD CONSTRAINT approval_policies_currency_check
                    CHECK (currency ~ '^[A-Z]{3}$');
                ALTER TABLE supplier_price_versions
                    ADD CONSTRAINT supplier_prices_currency_check
                    CHECK (currency ~ '^[A-Z]{3}$');
                ALTER TABLE supplier_products
                    ADD CONSTRAINT supplier_products_quality_status_check
                    CHECK (quality_status IN ('qualified', 'conditional', 'blocked'));
                ALTER TABLE approval_policy_steps
                    ADD CONSTRAINT approval_policy_steps_mode_check
                    CHECK (decision_mode IN ('any_one', 'all'));
                ALTER TABLE approval_policies
                    ADD CONSTRAINT approval_policies_no_overlap
                    EXCLUDE USING gist (
                        currency WITH =,
                        numrange(min_amount, max_amount, '[)') WITH &&,
                        tstzrange(active_from, active_until, '[)') WITH &&
                    ) WHERE (is_active);
                ALTER TABLE supplier_price_versions
                    ADD CONSTRAINT supplier_prices_no_overlap
                    EXCLUDE USING gist (
                        supplier_product_id WITH =,
                        currency WITH =,
                        minimum_quantity WITH =,
                        tstzrange(valid_from, valid_until, '[)') WITH &&
                    );
                CREATE TRIGGER supplier_products_set_updated_at
                BEFORE UPDATE ON supplier_products
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER approval_policies_set_updated_at
                BEFORE UPDATE ON approval_policies
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS approval_policies_set_updated_at ON approval_policies;
                DROP TRIGGER IF EXISTS supplier_products_set_updated_at ON supplier_products;
                ALTER TABLE supplier_price_versions DROP CONSTRAINT IF EXISTS supplier_prices_no_overlap;
                ALTER TABLE approval_policies DROP CONSTRAINT IF EXISTS approval_policies_no_overlap;
                ALTER TABLE approval_policy_steps DROP CONSTRAINT IF EXISTS approval_policy_steps_mode_check;
                ALTER TABLE supplier_products DROP CONSTRAINT IF EXISTS supplier_products_quality_status_check;
                ALTER TABLE supplier_price_versions DROP CONSTRAINT IF EXISTS supplier_prices_currency_check;
                ALTER TABLE approval_policies DROP CONSTRAINT IF EXISTS approval_policies_currency_check;
            """,
        ),
    ]
