# Generated by Django 5.2.17 on 2026-08-28 13:11

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_permission_rolepermission_userrole"),
        ("crm", "0002_supplier_code_supplier_contact_supplier_is_active_and_more"),
        ("erp", "0002_productcategory_product_description_and_more"),
        ("procurement", "0004_approvalpolicy_supplierproduct_supplierpriceversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_no", models.CharField(db_comment="採購需求唯一單號", max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("sourcing", "sourcing"),
                            ("awarding", "awarding"),
                            ("approval", "approval"),
                            ("ordered", "ordered"),
                            ("partially_received", "partially_received"),
                            ("completed", "completed"),
                            ("withdrawn", "withdrawn"),
                            ("cancelled", "cancelled"),
                        ],
                        db_comment="狀態：draft/submitted/sourcing/awarding/approval/ordered/partially_received/completed/withdrawn/cancelled",
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("purpose", models.TextField(db_comment="採購目的")),
                ("needed_by", models.DateField(blank=True, db_comment="期望到貨日期", null=True)),
                ("currency", models.CharField(db_comment="ISO 4217 三碼大寫幣別", default="TWD", max_length=3)),
                (
                    "source",
                    models.CharField(db_comment="需求來源，例如 manual/ai/legacy", default="manual", max_length=30),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_comment="防止重複提交的唯一鍵；草稿可為 NULL",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_comment="樂觀鎖版本，必須大於 0", default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_comment="建立時間（由資料庫產生）",
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_comment="最後更新時間（由資料庫 trigger 維護）",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "legacy_quote",
                    models.OneToOneField(
                        blank=True,
                        db_column="legacy_quote_id",
                        db_comment="對應舊 quotes.id；僅舊資料回填使用",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="migrated_purchase_request",
                        to="procurement.quote",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        db_column="requester_id",
                        db_comment="提出需求的 users.id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_requests",
                "db_table_comment": "企業採購需求單；可包含多筆需求明細",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.PositiveIntegerField(db_comment="需求單內行號，從 1 開始")),
                ("description_snapshot", models.TextField(db_comment="提交時的品項名稱與描述快照")),
                ("specification_snapshot", models.JSONField(db_comment="提交時的規格 JSON object 快照", default=dict)),
                ("quantity", models.DecimalField(db_comment="需求數量，必須大於 0", decimal_places=3, max_digits=14)),
                ("unit_of_measure", models.CharField(db_comment="計量單位快照，例如 EA、KG", max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_comment="建立時間（由資料庫產生）",
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_column="product_id",
                        db_comment="對應 products.id；尚未建立正式品項時可為 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_request_items",
                        to="erp.product",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        db_comment="對應 purchase_requests.id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_request_items",
                "db_table_comment": "採購需求明細與不可變品項規格快照",
            },
        ),
        migrations.CreateModel(
            name="RequestItemRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_comment="需求條件代碼", max_length=50)),
                ("label", models.CharField(db_comment="使用者可讀的條件名稱", max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("string", "string"), ("number", "number"), ("boolean", "boolean"), ("enum", "enum")],
                        db_comment="資料型別：string/number/boolean/enum",
                        max_length=20,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "equals"),
                            ("not_equals", "not_equals"),
                            ("gte", "gte"),
                            ("lte", "lte"),
                            ("in", "in"),
                            ("contains", "contains"),
                        ],
                        db_comment="比較運算子：equals/not_equals/gte/lte/in/contains",
                        max_length=20,
                    ),
                ),
                ("expected_value", models.JSONField(db_comment="預期值 JSON scalar 或 array")),
                ("is_mandatory", models.BooleanField(db_comment="是否為不得忽略的必要條件", default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_comment="建立時間（由資料庫產生）",
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "request_item",
                    models.ForeignKey(
                        db_column="request_item_id",
                        db_comment="對應 purchase_request_items.id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="procurement.purchaserequestitem",
                    ),
                ),
            ],
            options={
                "db_table": "request_item_requirements",
                "db_table_comment": "需求明細的規格與必要條件快照",
            },
        ),
        migrations.CreateModel(
            name="Rfq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rfq_no", models.CharField(db_comment="詢價單業務單號；不同 revision 共用", max_length=50)),
                ("revision", models.PositiveIntegerField(db_comment="詢價修訂版次，從 1 開始", default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("issued", "issued"),
                            ("collecting", "collecting"),
                            ("evaluating", "evaluating"),
                            ("closed", "closed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_comment="狀態：draft/issued/collecting/evaluating/closed/cancelled",
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("response_due_at", models.DateTimeField(blank=True, db_comment="供應商回覆期限", null=True)),
                ("rule_snapshot", models.JSONField(db_comment="評選規則與權重 JSON object 快照", default=dict)),
                ("version", models.PositiveIntegerField(db_comment="樂觀鎖版本，必須大於 0", default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_comment="建立時間（由資料庫產生）",
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_comment="最後更新時間（由資料庫 trigger 維護）",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        db_comment="對應 purchase_requests.id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfqs",
                        to="procurement.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "rfqs",
                "db_table_comment": "多供應商詢價單及其修訂版本",
            },
        ),
        migrations.CreateModel(
            name="RfqSupplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "invited"),
                            ("responded", "responded"),
                            ("declined", "declined"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                        ],
                        db_comment="狀態：invited/responded/declined/expired/cancelled",
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(db_comment="發出邀請時間")),
                ("responded_at", models.DateTimeField(blank=True, db_comment="供應商回覆時間", null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_comment="建立時間（由資料庫產生）",
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_comment="最後更新時間（由資料庫 trigger 維護）",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        db_column="rfq_id",
                        db_comment="對應 rfqs.id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_suppliers",
                        to="procurement.rfq",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        db_comment="受邀 suppliers.id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_invitations",
                        to="crm.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "rfq_suppliers",
                "db_table_comment": "RFQ 與受邀供應商的獨立狀態",
            },
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(fields=["requester", "status"], name="pr_requester_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaserequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="purchase_requests_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestitem",
            constraint=models.UniqueConstraint(
                fields=("request", "line_no"), name="purchase_request_items_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_no__gt", 0)), name="purchase_request_items_line_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="purchase_request_items_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="requestitemrequirement",
            constraint=models.UniqueConstraint(
                fields=("request_item", "code"), name="request_item_requirements_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rfq",
            constraint=models.UniqueConstraint(fields=("rfq_no", "revision"), name="rfqs_number_revision_unique"),
        ),
        migrations.AddConstraint(
            model_name="rfq",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "issued", "collecting", "evaluating"])),
                fields=("request",),
                name="rfqs_one_active_per_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfq",
            constraint=models.CheckConstraint(condition=models.Q(("revision__gt", 0)), name="rfqs_revision_positive"),
        ),
        migrations.AddConstraint(
            model_name="rfq",
            constraint=models.CheckConstraint(condition=models.Q(("version__gt", 0)), name="rfqs_version_positive"),
        ),
        migrations.AddConstraint(
            model_name="rfqsupplier",
            constraint=models.UniqueConstraint(fields=("rfq", "supplier"), name="rfq_suppliers_pair_unique"),
        ),
        migrations.AddConstraint(
            model_name="rfqsupplier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("responded_at__isnull", True), ("responded_at__gte", models.F("invited_at")), _connector="OR"
                ),
                name="rfq_suppliers_response_after_invite",
            ),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE purchase_requests
                    ADD CONSTRAINT purchase_requests_currency_check
                    CHECK (currency ~ '^[A-Z]{3}$'),
                    ADD CONSTRAINT purchase_requests_status_check
                    CHECK (status IN (
                        'draft', 'submitted', 'sourcing', 'awarding', 'approval',
                        'ordered', 'partially_received', 'completed', 'withdrawn', 'cancelled'
                    )),
                    ADD CONSTRAINT purchase_requests_idempotency_key_check
                    CHECK (idempotency_key IS NULL OR btrim(idempotency_key) <> '');
                ALTER TABLE purchase_request_items
                    ADD CONSTRAINT purchase_request_items_spec_object_check
                    CHECK (jsonb_typeof(specification_snapshot) = 'object');
                ALTER TABLE request_item_requirements
                    ADD CONSTRAINT request_item_requirements_data_type_check
                    CHECK (data_type IN ('string', 'number', 'boolean', 'enum')),
                    ADD CONSTRAINT request_item_requirements_operator_check
                    CHECK (operator IN ('equals', 'not_equals', 'gte', 'lte', 'in', 'contains'));
                ALTER TABLE rfqs
                    ADD CONSTRAINT rfqs_status_check
                    CHECK (status IN ('draft', 'issued', 'collecting', 'evaluating', 'closed', 'cancelled')),
                    ADD CONSTRAINT rfqs_rule_object_check
                    CHECK (jsonb_typeof(rule_snapshot) = 'object');
                ALTER TABLE rfq_suppliers
                    ADD CONSTRAINT rfq_suppliers_status_check
                    CHECK (status IN ('invited', 'responded', 'declined', 'expired', 'cancelled'));
                CREATE TRIGGER purchase_requests_set_updated_at
                BEFORE UPDATE ON purchase_requests
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER rfqs_set_updated_at
                BEFORE UPDATE ON rfqs
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER rfq_suppliers_set_updated_at
                BEFORE UPDATE ON rfq_suppliers
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS rfq_suppliers_set_updated_at ON rfq_suppliers;
                DROP TRIGGER IF EXISTS rfqs_set_updated_at ON rfqs;
                DROP TRIGGER IF EXISTS purchase_requests_set_updated_at ON purchase_requests;
                ALTER TABLE rfq_suppliers DROP CONSTRAINT IF EXISTS rfq_suppliers_status_check;
                ALTER TABLE rfqs DROP CONSTRAINT IF EXISTS rfqs_rule_object_check;
                ALTER TABLE rfqs DROP CONSTRAINT IF EXISTS rfqs_status_check;
                ALTER TABLE request_item_requirements DROP CONSTRAINT IF EXISTS
                    request_item_requirements_operator_check;
                ALTER TABLE request_item_requirements DROP CONSTRAINT IF EXISTS
                    request_item_requirements_data_type_check;
                ALTER TABLE purchase_request_items DROP CONSTRAINT IF EXISTS purchase_request_items_spec_object_check;
                ALTER TABLE purchase_requests DROP CONSTRAINT IF EXISTS purchase_requests_idempotency_key_check;
                ALTER TABLE purchase_requests DROP CONSTRAINT IF EXISTS purchase_requests_status_check;
                ALTER TABLE purchase_requests DROP CONSTRAINT IF EXISTS purchase_requests_currency_check;
            """,
        ),
    ]
