# Generated by Django 5.2.17 on 2026-08-28 13:22

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('procurement', '0005_purchaserequest_purchaserequestitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqScoringCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='評分準則代碼', max_length=50)),
                ('label', models.CharField(db_comment='使用者可讀的評分準則名稱', max_length=100)),
                ('weight', models.DecimalField(db_comment='百分比權重，必須大於 0 且不超過 100', decimal_places=2, max_digits=5)),
                ('calculation_method', models.CharField(db_comment='Django 固定計算方法代碼', max_length=50)),
                ('sequence', models.PositiveIntegerField(db_comment='畫面與計算順序，從 1 開始')),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('rfq', models.ForeignKey(db_column='rfq_id', db_comment='對應 rfqs.id', on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='procurement.rfq')),
            ],
            options={
                'db_table': 'rfq_scoring_criteria',
                'db_table_comment': 'RFQ 的不可變評分準則與權重快照',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(db_comment='供應商報價業務單號；不同 revision 共用', max_length=50)),
                ('revision', models.PositiveIntegerField(db_comment='報價修訂版次，從 1 開始', default=1)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('accepted_for_evaluation', 'accepted_for_evaluation'), ('revised', 'revised'), ('rejected', 'rejected'), ('expired', 'expired')], db_comment='狀態：draft/submitted/accepted_for_evaluation/revised/rejected/expired', default='draft', max_length=30)),
                ('currency', models.CharField(db_comment='原始報價 ISO 4217 三碼大寫幣別', max_length=3)),
                ('exchange_rate_to_twd', models.DecimalField(db_comment='換算 TWD 的匯率快照，必須大於 0', decimal_places=6, max_digits=18)),
                ('items_subtotal', models.DecimalField(db_comment='原幣品項小計', decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(db_comment='原幣稅額', decimal_places=2, default=0, max_digits=14)),
                ('shipping_amount', models.DecimalField(db_comment='原幣運費', decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(db_comment='原幣折扣', decimal_places=2, default=0, max_digits=14)),
                ('landed_total_twd', models.DecimalField(db_comment='換算後實際總成本 TWD', decimal_places=2, max_digits=14)),
                ('payment_terms_snapshot', models.TextField(blank=True, db_comment='付款條件快照')),
                ('valid_until', models.DateTimeField(blank=True, db_comment='報價有效期限', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='正式提交時間', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('rfq_supplier', models.ForeignKey(db_column='rfq_supplier_id', db_comment='對應 rfq_suppliers.id，決定 RFQ 與供應商', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='procurement.rfqsupplier')),
            ],
            options={
                'db_table': 'supplier_quotes',
                'db_table_comment': '供應商針對 RFQ 提交的版本化正式報價快照',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_comment='報價數量，必須大於 0', decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(db_comment='原幣未稅單價', decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(db_comment='原幣品項小計', decimal_places=2, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, db_comment='交期天數', null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, db_comment='保固月數', null=True)),
                ('specification_snapshot', models.JSONField(db_comment='供應商回覆的規格 JSON object 快照', default=dict)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('request_item', models.ForeignKey(db_column='request_item_id', db_comment='對應 purchase_request_items.id', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quote_items', to='procurement.purchaserequestitem')),
                ('supplier_quote', models.ForeignKey(db_column='supplier_quote_id', db_comment='對應 supplier_quotes.id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplierquote')),
            ],
            options={
                'db_table': 'supplier_quote_items',
                'db_table_comment': '供應商報價的逐項商務與規格快照',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequirementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('not_provided', 'not_provided'), ('waived', 'waived')], db_comment='結果：pass/fail/not_provided/waived', max_length=20)),
                ('evidence', models.TextField(blank=True, db_comment='供應商證明或系統比對依據')),
                ('waiver_reason', models.TextField(blank=True, db_comment='例外採用理由；waived 時必填', null=True)),
                ('waived_at', models.DateTimeField(blank=True, db_comment='例外核准時間；waived 時必填', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('requirement', models.ForeignKey(db_column='requirement_id', db_comment='對應 request_item_requirements.id', on_delete=django.db.models.deletion.PROTECT, related_name='quote_results', to='procurement.requestitemrequirement')),
                ('waived_by', models.ForeignKey(blank=True, db_column='waived_by_id', db_comment='例外核准的 users.id；waived 時必填', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quote_requirement_waivers', to='core.user')),
                ('quote_item', models.ForeignKey(db_column='quote_item_id', db_comment='對應 supplier_quote_items.id', on_delete=django.db.models.deletion.CASCADE, related_name='requirement_results', to='procurement.supplierquoteitem')),
            ],
            options={
                'db_table': 'quote_requirement_results',
                'db_table_comment': '報價明細對必要與偏好條件的符合結果',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.JSONField(db_comment='固定公式使用的原始值快照 JSON object', default=dict)),
                ('normalized_score', models.DecimalField(db_comment='標準化分數 0 到 100', decimal_places=2, max_digits=5)),
                ('weighted_score', models.DecimalField(db_comment='套用權重後分數 0 到 100', decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('criterion', models.ForeignKey(db_column='criterion_id', db_comment='對應 rfq_scoring_criteria.id', on_delete=django.db.models.deletion.PROTECT, related_name='quote_scores', to='procurement.rfqscoringcriterion')),
                ('supplier_quote', models.ForeignKey(db_column='supplier_quote_id', db_comment='對應 supplier_quotes.id', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='procurement.supplierquote')),
            ],
            options={
                'db_table': 'supplier_quote_scores',
                'db_table_comment': '供應商報價的固定公式評分快照；AI 不得寫入',
            },
        ),
        migrations.AddConstraint(
            model_name='rfqscoringcriterion',
            constraint=models.UniqueConstraint(fields=('rfq', 'code'), name='rfq_scoring_criteria_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='rfqscoringcriterion',
            constraint=models.UniqueConstraint(fields=('rfq', 'sequence'), name='rfq_scoring_criteria_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='rfqscoringcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 100)), name='rfq_scoring_criteria_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='rfqscoringcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='rfq_scoring_criteria_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.UniqueConstraint(fields=('quote_no', 'revision'), name='supplier_quotes_number_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.UniqueConstraint(fields=('rfq_supplier', 'revision'), name='supplier_quotes_invitation_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'accepted_for_evaluation'])), fields=('rfq_supplier',), name='supplier_quotes_one_active_invitation'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='supplier_quotes_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='supplier_quotes_currency_format'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate_to_twd__gt', 0)), name='supplier_quotes_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('items_subtotal__gte', 0), ('tax_amount__gte', 0), ('shipping_amount__gte', 0), ('discount_amount__gte', 0), ('landed_total_twd__gte', 0)), name='supplier_quotes_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteitem',
            constraint=models.UniqueConstraint(fields=('supplier_quote', 'request_item'), name='supplier_quote_items_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supplier_quote_items_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('subtotal__gte', 0)), name='supplier_quote_items_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quoterequirementresult',
            constraint=models.UniqueConstraint(fields=('quote_item', 'requirement'), name='quote_requirement_results_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='quoterequirementresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result', 'waived'), ('waived_at__isnull', False), ('waived_by__isnull', False), ('waiver_reason__isnull', False), models.Q(('waiver_reason', ''), _negated=True)), models.Q(models.Q(('result', 'waived'), _negated=True), ('waived_at__isnull', True), ('waived_by__isnull', True), ('waiver_reason__isnull', True)), _connector='OR'), name='quote_requirement_results_waiver_complete'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotescore',
            constraint=models.UniqueConstraint(fields=('supplier_quote', 'criterion'), name='supplier_quote_scores_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotescore',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_score__gte', 0), ('normalized_score__lte', 100)), name='supplier_quote_scores_normalized_range'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotescore',
            constraint=models.CheckConstraint(condition=models.Q(('weighted_score__gte', 0), ('weighted_score__lte', 100)), name='supplier_quote_scores_weighted_range'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE supplier_quotes
                    ADD CONSTRAINT supplier_quotes_status_check
                    CHECK (status IN (
                        'draft', 'submitted', 'accepted_for_evaluation',
                        'revised', 'rejected', 'expired'
                    ));
                ALTER TABLE supplier_quote_items
                    ADD CONSTRAINT supplier_quote_items_spec_object_check
                    CHECK (jsonb_typeof(specification_snapshot) = 'object');
                ALTER TABLE quote_requirement_results
                    ADD CONSTRAINT quote_requirement_results_result_check
                    CHECK (result IN ('pass', 'fail', 'not_provided', 'waived'));
                ALTER TABLE supplier_quote_scores
                    ADD CONSTRAINT supplier_quote_scores_raw_object_check
                    CHECK (jsonb_typeof(raw_value) = 'object');

                CREATE OR REPLACE FUNCTION enforce_rfq_scoring_weight_total()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    target_rfq_id bigint;
                    target_status varchar;
                    total_weight numeric;
                BEGIN
                    IF TG_TABLE_NAME = 'rfqs' THEN
                        target_rfq_id := NEW.id;
                    ELSIF TG_OP = 'DELETE' THEN
                        target_rfq_id := OLD.rfq_id;
                    ELSE
                        target_rfq_id := NEW.rfq_id;
                    END IF;
                    SELECT status INTO target_status FROM rfqs WHERE id = target_rfq_id;
                    IF target_status IN ('issued', 'collecting', 'evaluating', 'closed') THEN
                        SELECT COALESCE(SUM(weight), 0) INTO total_weight
                        FROM rfq_scoring_criteria WHERE rfq_id = target_rfq_id;
                        IF total_weight <> 100 THEN
                            RAISE EXCEPTION 'RFQ scoring criteria weights must total 100'
                                USING ERRCODE = 'check_violation';
                        END IF;
                    END IF;
                    RETURN COALESCE(NEW, OLD);
                END;
                $$;

                CREATE TRIGGER rfqs_scoring_weight_total_check
                AFTER INSERT OR UPDATE OF status ON rfqs
                FOR EACH ROW EXECUTE FUNCTION enforce_rfq_scoring_weight_total();
                CREATE CONSTRAINT TRIGGER rfq_criteria_weight_total_check
                AFTER INSERT OR UPDATE OR DELETE ON rfq_scoring_criteria
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW EXECUTE FUNCTION enforce_rfq_scoring_weight_total();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS rfq_criteria_weight_total_check ON rfq_scoring_criteria;
                DROP TRIGGER IF EXISTS rfqs_scoring_weight_total_check ON rfqs;
                DROP FUNCTION IF EXISTS enforce_rfq_scoring_weight_total();
                ALTER TABLE supplier_quote_scores DROP CONSTRAINT IF EXISTS supplier_quote_scores_raw_object_check;
                ALTER TABLE quote_requirement_results DROP CONSTRAINT IF EXISTS quote_requirement_results_result_check;
                ALTER TABLE supplier_quote_items DROP CONSTRAINT IF EXISTS supplier_quote_items_spec_object_check;
                ALTER TABLE supplier_quotes DROP CONSTRAINT IF EXISTS supplier_quotes_status_check;
            """,
        ),
    ]
