# Generated by Django 5.2.17 on 2026-08-28 13:41

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('crm', '0002_supplier_code_supplier_contact_supplier_is_active_and_more'),
        ('erp', '0002_productcategory_product_description_and_more'),
        ('procurement', '0006_supplierquote_rfqscoringcriterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(db_comment='得標方案版次，從 1 開始', default=1)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], db_comment='狀態：draft/submitted/approved/rejected/cancelled', default='draft', max_length=20)),
                ('selection_reason', models.TextField(db_comment='人工選商理由')),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='送出簽核時間', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('recommended_quote', models.ForeignKey(blank=True, db_column='recommended_quote_id', db_comment='系統建議的 supplier_quotes.id；逐項得標時可為 NULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommended_awards', to='procurement.supplierquote')),
                ('rfq', models.ForeignKey(db_column='rfq_id', db_comment='對應 rfqs.id', on_delete=django.db.models.deletion.PROTECT, related_name='award_decisions', to='procurement.rfq')),
                ('selected_by', models.ForeignKey(db_column='selected_by_id', db_comment='建立選商方案的 users.id', on_delete=django.db.models.deletion.PROTECT, related_name='selected_awards', to='core.user')),
            ],
            options={
                'db_table': 'award_decisions',
                'db_table_comment': '得標選商方案版本',
            },
        ),
        migrations.CreateModel(
            name='ApprovalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_snapshot', models.JSONField(db_comment='案件建立時的簽核政策 JSON object 快照', default=dict)),
                ('total_amount', models.DecimalField(db_comment='得標後實際總金額', decimal_places=2, max_digits=14)),
                ('currency', models.CharField(db_comment='ISO 4217 三碼大寫幣別', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], db_comment='狀態：pending/in_progress/approved/rejected/cancelled', default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(db_comment='簽核案件建立時間')),
                ('decided_at', models.DateTimeField(blank=True, db_comment='最終決議時間', null=True)),
                ('version', models.PositiveIntegerField(db_comment='樂觀鎖版本，必須大於 0', default=1)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
                ('policy', models.ForeignKey(db_column='policy_id', db_comment='產生案件的 approval_policies.id', on_delete=django.db.models.deletion.PROTECT, related_name='approval_cases', to='procurement.approvalpolicy')),
                ('requester', models.ForeignKey(db_column='requester_id', db_comment='不得決議本案的原始申請人 users.id', on_delete=django.db.models.deletion.PROTECT, related_name='requested_approval_cases', to='core.user')),
                ('award', models.OneToOneField(db_column='award_id', db_comment='對應 award_decisions.id', on_delete=django.db.models.deletion.PROTECT, related_name='approval_case', to='procurement.awarddecision')),
            ],
            options={
                'db_table': 'approval_cases',
                'db_table_comment': '得標方案的多關簽核案件',
            },
        ),
        migrations.CreateModel(
            name='AwardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_quantity', models.DecimalField(db_comment='得標數量，必須大於 0', decimal_places=3, max_digits=14)),
                ('unit_price_snapshot', models.DecimalField(db_comment='得標時單價快照', decimal_places=2, max_digits=14)),
                ('amount_snapshot', models.DecimalField(db_comment='得標時金額快照', decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True, db_comment='逐項選商或拆量理由')),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('award', models.ForeignKey(db_column='award_id', db_comment='對應 award_decisions.id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.awarddecision')),
                ('request_item', models.ForeignKey(db_column='request_item_id', db_comment='對應 purchase_request_items.id', on_delete=django.db.models.deletion.PROTECT, related_name='award_lines', to='procurement.purchaserequestitem')),
                ('supplier_quote_item', models.ForeignKey(db_column='supplier_quote_item_id', db_comment='對應 supplier_quote_items.id', on_delete=django.db.models.deletion.PROTECT, related_name='award_lines', to='procurement.supplierquoteitem')),
            ],
            options={
                'db_table': 'award_lines',
                'db_table_comment': '得標方案的逐品項與拆量結果',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(db_comment='採購單唯一單號', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('partially_received', 'partially_received'), ('received', 'received'), ('closed', 'closed'), ('cancelled', 'cancelled')], db_comment='狀態：draft/issued/partially_received/received/closed/cancelled', default='draft', max_length=30)),
                ('currency', models.CharField(db_comment='ISO 4217 三碼大寫幣別', max_length=3)),
                ('total_amount', models.DecimalField(db_comment='採購單總金額快照', decimal_places=2, max_digits=14)),
                ('issued_at', models.DateTimeField(blank=True, db_comment='發單時間', null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_comment='結案時間', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_comment='取消時間', null=True)),
                ('version', models.PositiveIntegerField(db_comment='樂觀鎖版本，必須大於 0', default=1)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
                ('award', models.ForeignKey(db_column='award_id', db_comment='對應 award_decisions.id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.awarddecision')),
                ('supplier', models.ForeignKey(db_column='supplier_id', db_comment='得標供應商 suppliers.id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='crm.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
                'db_table_comment': '得標核准後依供應商拆分的正式採購單',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(db_comment='採購單內行號，從 1 開始')),
                ('product_name_snapshot', models.TextField(db_comment='正式下單時的品項名稱快照')),
                ('specification_snapshot', models.JSONField(db_comment='正式下單時的規格 JSON object 快照', default=dict)),
                ('ordered_quantity', models.DecimalField(db_comment='訂購數量，必須大於 0', decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(db_comment='正式下單單價快照', decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(db_comment='正式下單金額快照', decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('award_line', models.OneToOneField(db_column='award_line_id', db_comment='對應 award_lines.id', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_item', to='procurement.awardline')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', db_comment='對應 products.id；同時保留名稱與規格快照', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='erp.product')),
                ('purchase_order', models.ForeignKey(db_column='purchase_order_id', db_comment='對應 purchase_orders.id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
                'db_table_comment': '正式採購單品項、規格、價格與數量快照',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_comment='簽核順序，從 1 開始')),
                ('role_snapshot', models.JSONField(db_comment='關卡建立時的角色與決議規則 JSON object 快照', default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('claimed', 'claimed'), ('approved', 'approved'), ('rejected', 'rejected')], db_comment='狀態：pending/claimed/approved/rejected', default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, db_comment='認領時間', null=True)),
                ('decided_at', models.DateTimeField(blank=True, db_comment='決議時間', null=True)),
                ('decision_reason', models.TextField(blank=True, db_comment='核准或駁回理由', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
                ('approval_case', models.ForeignKey(db_column='approval_case_id', db_comment='對應 approval_cases.id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procurement.approvalcase')),
                ('claimed_by', models.ForeignKey(blank=True, db_column='claimed_by_id', db_comment='認領人 users.id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_approval_steps', to='core.user')),
                ('decided_by', models.ForeignKey(blank=True, db_column='decided_by_id', db_comment='決議人 users.id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approval_steps', to='core.user')),
                ('role', models.ForeignKey(db_column='role_id', db_comment='可認領此關卡的 roles.id', on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='core.role')),
            ],
            options={
                'db_table': 'approval_steps',
                'db_table_comment': '簽核案件的角色關卡、認領與決議紀錄',
                'constraints': [models.UniqueConstraint(fields=('approval_case', 'sequence'), name='approval_steps_case_sequence_unique'), models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='approval_steps_sequence_positive'), models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('claimed_by__isnull', True), ('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason__isnull', True), ('status', 'pending')), models.Q(('claimed_at__isnull', False), ('claimed_by__isnull', False), ('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason__isnull', True), ('status', 'claimed')), models.Q(('claimed_at__isnull', False), ('claimed_by__isnull', False), ('decided_at__isnull', False), ('decided_by__isnull', False), ('decision_reason__isnull', False), ('status__in', ['approved', 'rejected']), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='approval_steps_actor_fields_consistent')],
            },
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.UniqueConstraint(fields=('rfq', 'revision'), name='award_decisions_rfq_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'approved'])), fields=('rfq',), name='award_decisions_one_active_rfq'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='award_decisions_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('submitted_at__isnull', True)), models.Q(models.Q(('status', 'draft'), _negated=True), ('submitted_at__isnull', False)), _connector='OR'), name='award_decisions_submission_time_consistent'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='approval_cases_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='approval_cases_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='approval_cases_currency_format'),
        ),
        migrations.AddConstraint(
            model_name='awardline',
            constraint=models.UniqueConstraint(fields=('award', 'supplier_quote_item'), name='award_lines_quote_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='awardline',
            constraint=models.CheckConstraint(condition=models.Q(('awarded_quantity__gt', 0)), name='award_lines_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='awardline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 0), ('amount_snapshot__gte', 0)), name='award_lines_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('award', 'supplier'), name='purchase_orders_award_supplier_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='purchase_orders_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='purchase_orders_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='purchase_orders_currency_format'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_no'), name='purchase_order_items_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gt', 0)), name='purchase_order_items_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', 0)), name='purchase_order_items_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('amount__gte', 0)), name='purchase_order_items_amounts_nonnegative'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE award_decisions ADD CONSTRAINT award_decisions_status_check
                    CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'cancelled'));
                ALTER TABLE approval_cases ADD CONSTRAINT approval_cases_status_check
                    CHECK (status IN ('pending', 'in_progress', 'approved', 'rejected', 'cancelled'));
                ALTER TABLE approval_cases ADD CONSTRAINT approval_cases_policy_object_check
                    CHECK (jsonb_typeof(policy_snapshot) = 'object');
                ALTER TABLE approval_steps ADD CONSTRAINT approval_steps_status_check
                    CHECK (status IN ('pending', 'claimed', 'approved', 'rejected'));
                ALTER TABLE approval_steps ADD CONSTRAINT approval_steps_role_object_check
                    CHECK (jsonb_typeof(role_snapshot) = 'object');
                ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_status_check
                    CHECK (status IN ('draft', 'issued', 'partially_received', 'received', 'closed', 'cancelled'));
                ALTER TABLE purchase_order_items ADD CONSTRAINT purchase_order_items_spec_object_check
                    CHECK (jsonb_typeof(specification_snapshot) = 'object');

                CREATE TRIGGER approval_cases_set_updated_at BEFORE UPDATE ON approval_cases
                    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER approval_steps_set_updated_at BEFORE UPDATE ON approval_steps
                    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER purchase_orders_set_updated_at BEFORE UPDATE ON purchase_orders
                    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();

                CREATE OR REPLACE FUNCTION enforce_award_line_relationships()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    award_request_id bigint;
                    quote_request_id bigint;
                    quote_item_request_id bigint;
                BEGIN
                    SELECT r.request_id INTO award_request_id
                    FROM award_decisions a JOIN rfqs r ON r.id = a.rfq_id
                    WHERE a.id = NEW.award_id;
                    SELECT rs.rfq_id, sqi.request_item_id
                    INTO quote_request_id, quote_item_request_id
                    FROM supplier_quote_items sqi
                    JOIN supplier_quotes sq ON sq.id = sqi.supplier_quote_id
                    JOIN rfq_suppliers rs ON rs.id = sq.rfq_supplier_id
                    WHERE sqi.id = NEW.supplier_quote_item_id;
                    SELECT r.request_id INTO quote_request_id FROM rfqs r WHERE r.id = quote_request_id;
                    IF NOT EXISTS (
                        SELECT 1 FROM purchase_request_items pri
                        WHERE pri.id = NEW.request_item_id AND pri.request_id = award_request_id
                    ) OR quote_item_request_id <> NEW.request_item_id OR quote_request_id <> award_request_id THEN
                        RAISE EXCEPTION 'award line references inconsistent request or quote item'
                            USING ERRCODE = 'foreign_key_violation';
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER award_lines_relationship_check
                    BEFORE INSERT OR UPDATE OF award_id, request_item_id, supplier_quote_item_id ON award_lines
                    FOR EACH ROW EXECUTE FUNCTION enforce_award_line_relationships();

                CREATE OR REPLACE FUNCTION enforce_award_allocation_complete()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    target_award_id bigint;
                    target_status varchar;
                    mismatch_exists boolean;
                BEGIN
                    IF TG_TABLE_NAME = 'award_decisions' THEN
                        target_award_id := NEW.id;
                    ELSIF TG_OP = 'DELETE' THEN
                        target_award_id := OLD.award_id;
                    ELSE
                        target_award_id := NEW.award_id;
                    END IF;
                    SELECT status INTO target_status FROM award_decisions WHERE id = target_award_id;
                    IF target_status = 'submitted' THEN
                        SELECT EXISTS (
                            SELECT 1
                            FROM purchase_request_items pri
                            JOIN rfqs r ON r.request_id = pri.request_id
                            JOIN award_decisions a ON a.rfq_id = r.id AND a.id = target_award_id
                            LEFT JOIN award_lines al ON al.award_id = a.id AND al.request_item_id = pri.id
                            GROUP BY pri.id, pri.quantity
                            HAVING COALESCE(SUM(al.awarded_quantity), 0) <> pri.quantity
                        ) INTO mismatch_exists;
                        IF mismatch_exists THEN
                            RAISE EXCEPTION 'submitted award quantities must exactly match request quantities'
                                USING ERRCODE = 'check_violation';
                        END IF;
                    END IF;
                    RETURN COALESCE(NEW, OLD);
                END;
                $$;
                CREATE TRIGGER award_decisions_allocation_check
                    AFTER INSERT OR UPDATE OF status ON award_decisions
                    FOR EACH ROW EXECUTE FUNCTION enforce_award_allocation_complete();
                CREATE CONSTRAINT TRIGGER award_lines_allocation_check
                    AFTER INSERT OR UPDATE OR DELETE ON award_lines
                    DEFERRABLE INITIALLY DEFERRED
                    FOR EACH ROW EXECUTE FUNCTION enforce_award_allocation_complete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS award_lines_allocation_check ON award_lines;
                DROP TRIGGER IF EXISTS award_decisions_allocation_check ON award_decisions;
                DROP FUNCTION IF EXISTS enforce_award_allocation_complete();
                DROP TRIGGER IF EXISTS award_lines_relationship_check ON award_lines;
                DROP FUNCTION IF EXISTS enforce_award_line_relationships();
                DROP TRIGGER IF EXISTS purchase_orders_set_updated_at ON purchase_orders;
                DROP TRIGGER IF EXISTS approval_steps_set_updated_at ON approval_steps;
                DROP TRIGGER IF EXISTS approval_cases_set_updated_at ON approval_cases;
                ALTER TABLE purchase_order_items DROP CONSTRAINT IF EXISTS purchase_order_items_spec_object_check;
                ALTER TABLE purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_status_check;
                ALTER TABLE approval_steps DROP CONSTRAINT IF EXISTS approval_steps_role_object_check;
                ALTER TABLE approval_steps DROP CONSTRAINT IF EXISTS approval_steps_status_check;
                ALTER TABLE approval_cases DROP CONSTRAINT IF EXISTS approval_cases_policy_object_check;
                ALTER TABLE approval_cases DROP CONSTRAINT IF EXISTS approval_cases_status_check;
                ALTER TABLE award_decisions DROP CONSTRAINT IF EXISTS award_decisions_status_check;
            """,
        ),
    ]
