# Generated by Django 5.2.17 on 2026-08-30 02:43

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('procurement', '0009_backfill_legacy_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStepWaiver',
            fields=[
                ('id', models.BigAutoField(db_comment='簽核例外關聯 ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'approval_step_waivers',
                'db_table_comment': '簽核例外關卡與必要條件 waiver 的對照',
            },
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='waiver_role',
            field=models.ForeignKey(blank=True, db_column='waiver_role_id', db_comment='必要條件例外的獨立覆核角色 roles.id；NULL 表示政策未設定例外覆核', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiver_approval_policies', to='core.role'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='step_type',
            field=models.CharField(choices=[('waiver_exception', 'waiver_exception'), ('amount_approval', 'amount_approval')], db_comment='關卡類型：waiver_exception/amount_approval', default='amount_approval', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(condition=models.Q(('step_type__in', ['waiver_exception', 'amount_approval'])), name='approval_steps_type_valid'),
        ),
        migrations.AddField(
            model_name='approvalstepwaiver',
            name='approval_step',
            field=models.ForeignKey(db_column='approval_step_id', db_comment='對應 approval_steps.id，僅限 waiver_exception 關卡', on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='procurement.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalstepwaiver',
            name='quote_requirement_result',
            field=models.ForeignKey(db_column='quote_requirement_result_id', db_comment='對應 quote_requirement_results.id 的已核准 waiver', on_delete=django.db.models.deletion.PROTECT, related_name='approval_step_waivers', to='procurement.quoterequirementresult'),
        ),
        migrations.AddConstraint(
            model_name='approvalstepwaiver',
            constraint=models.UniqueConstraint(fields=('approval_step', 'quote_requirement_result'), name='approval_step_waivers_pair_unique'),
        ),
    ]
