# Generated by Django 5.2.17 on 2026-08-30 05:34

from django.db import migrations, models


FORWARD_SQL = """
ALTER TABLE purchase_requests DROP CONSTRAINT purchase_requests_status_check;
ALTER TABLE purchase_requests ADD CONSTRAINT purchase_requests_status_check
    CHECK (status IN (
        'draft', 'submitted', 'sourcing', 'awarding', 'approval', 'rejected',
        'ordered', 'partially_received', 'completed', 'withdrawn', 'cancelled'
    ));
"""

REVERSE_SQL = """
ALTER TABLE purchase_requests DROP CONSTRAINT purchase_requests_status_check;
ALTER TABLE purchase_requests ADD CONSTRAINT purchase_requests_status_check
    CHECK (status IN (
        'draft', 'submitted', 'sourcing', 'awarding', 'approval',
        'ordered', 'partially_received', 'completed', 'withdrawn', 'cancelled'
    ));
"""


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_approval_waiver_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('sourcing', 'sourcing'), ('awarding', 'awarding'), ('approval', 'approval'), ('rejected', 'rejected'), ('ordered', 'ordered'), ('partially_received', 'partially_received'), ('completed', 'completed'), ('withdrawn', 'withdrawn'), ('cancelled', 'cancelled')], db_comment='狀態：draft/submitted/sourcing/awarding/approval/rejected/ordered/partially_received/completed/withdrawn/cancelled', default='draft', max_length=30),
        ),
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
