# Generated by Django 5.2.17 on 2026-08-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50, unique=True)),
                (
                    "approval_amount_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="該角色的簽核金額上限；null＝無上限（admin 固定 null）；employee 不參與簽核路由",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "password",
                    models.CharField(
                        help_text="Django 內建雜湊儲存（PBKDF2），非明碼",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
