# Generated by Django 5.2.17 on 2026-08-27 13:26

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_comment='JWT 唯一識別碼，不含 Token 明文', max_length=36, unique=True)),
                ('token_hash', models.CharField(db_comment='Refresh Token 的 SHA-256 雜湊，不儲存 Token 明文', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_comment='Session 建立時間（由資料庫產生）', db_default=Now(), editable=False)),
                ('expires_at', models.DateTimeField(db_comment='Refresh Token 到期時間')),
                ('revoked_at', models.DateTimeField(blank=True, db_comment='撤銷時間；NULL 表示尚未撤銷', null=True)),
                ('replaced_by', models.ForeignKey(blank=True, db_column='replaced_by_id', db_comment='Rotation 後接替此 Token 的 refresh_sessions.id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.refreshsession')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='對應 users.id 的登入使用者', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to='core.user')),
            ],
            options={
                'db_table': 'refresh_sessions',
                'db_table_comment': '使用者 Refresh Token session，供 rotation、登出撤銷與重放防護使用',
                'indexes': [models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'expires_at'], name='refresh_user_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='refresh_sessions_expiry_check')],
            },
        ),
    ]
