# Generated by Django 5.2.17 on 2026-08-28 12:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


def backfill_primary_user_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    UserRole = apps.get_model('core', 'UserRole')
    UserRole.objects.bulk_create(
        [UserRole(user_id=user.id, role_id=user.role_id) for user in User.objects.all()],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refresh_session'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION set_row_updated_at()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    NEW.updated_at := now();
                    RETURN NEW;
                END;
                $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS set_row_updated_at();",
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='權限代碼，例如 purchase_request.create', max_length=100, unique=True)),
                ('name', models.CharField(db_comment='權限顯示名稱', max_length=100)),
                ('description', models.TextField(blank=True, db_comment='權限用途說明')),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'permissions',
                'db_table_comment': 'RBAC 權限主檔',
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='permissions_code_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('permission', models.ForeignKey(db_column='permission_id', db_comment='對應 permissions.id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
                ('role', models.ForeignKey(db_column='role_id', db_comment='對應 roles.id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'db_table_comment': 'RBAC 角色與權限對照',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='role_permissions_pair_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(db_comment='角色生效時間', db_default=django.db.models.functions.datetime.Now())),
                ('valid_until', models.DateTimeField(blank=True, db_comment='角色失效時間；NULL 表示持續有效', null=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by_id', db_comment='授予角色的 users.id；資料遷移可為 NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to='core.user')),
                ('role', models.ForeignKey(db_column='role_id', db_comment='授予的 roles.id', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='持有角色的 users.id', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.user')),
            ],
            options={
                'db_table': 'user_roles',
                'db_table_comment': '使用者與角色的多對多指派及有效期間',
                'indexes': [models.Index(fields=['user', 'valid_until'], name='user_roles_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='user_roles_user_role_unique'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='user_roles_valid_period_check')],
            },
        ),
        migrations.RunPython(backfill_primary_user_roles, migrations.RunPython.noop),
    ]
