# Generated by Django 5.2.17 on 2026-08-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="例如 llm_parse／hallucination_check／review_decision",
                        max_length=50,
                    ),
                ),
                (
                    "masked_payload",
                    models.TextField(
                        blank=True, help_text="送往 LLM 的脫敏內容", null=True
                    ),
                ),
                (
                    "real_query_summary",
                    models.TextField(
                        blank=True, help_text="查了哪張表的摘要", null=True
                    ),
                ),
                (
                    "verification_result",
                    models.CharField(
                        blank=True,
                        help_text="pass／fail／n/a",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        db_column="quote_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="procurement.quote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        help_text="觸發者；系統自動觸發時為 null",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="ManualReviewQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("hallucination_mismatch", "hallucination_mismatch"),
                            ("supplier_fuzzy_match", "supplier_fuzzy_match"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "ai_generated_text",
                    models.TextField(blank=True, help_text="幻覺案件用", null=True),
                ),
                (
                    "expected_value",
                    models.TextField(
                        blank=True,
                        help_text="原始真實數字（JSON），幻覺案件用",
                        null=True,
                    ),
                ),
                (
                    "raw_input_text",
                    models.TextField(
                        blank=True, help_text="模糊比對案件：使用者原始輸入", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unclaimed", "unclaimed"),
                            ("claimed", "claimed"),
                            ("resolved", "resolved"),
                        ],
                        default="unclaimed",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "approved"), ("rejected", "rejected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        db_column="quote_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_entries",
                        to="procurement.quote",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_column="supplier_id",
                        help_text="模糊比對案件：系統疑似比對到的供應商",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuzzy_review_entries",
                        to="crm.supplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        help_text="認領/處理的管理員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_review_entries",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "manual_review_queue",
            },
        ),
    ]
