# Generated by Django 5.2.17 on 2026-08-27 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualreviewqueue",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                db_column="quote_id",
                help_text="supplier_fuzzy_match 案件在 Mask 階段建立，尚無 Quote，此欄位為 null",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_entries",
                to="procurement.quote",
            ),
        ),
    ]
