# Generated by Django 5.2.17 on 2026-08-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_manualreviewqueue_quote"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualreviewqueue",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                db_column="requester_user_id",
                help_text="模糊比對案件：原始詢價發起人，核准後交還 n8n 重新觸發流程時要用來建立 Quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_review_entries",
                to="core.user",
            ),
        ),
    ]
