# Generated by Django 5.2.17 on 2026-09-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_manualreviewqueue_requester"),
        ("core", "0003_permission_rolepermission_userrole"),
        ("crm", "0002_supplier_code_supplier_contact_supplier_is_active_and_more"),
        ("procurement", "0011_purchase_request_rejected_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualreviewqueue",
            name="created_purchase_request",
            field=models.ForeignKey(
                blank=True,
                db_column="created_purchase_request_id",
                help_text="resume_status=succeeded 時續傳流程自動建立的採購需求草稿",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumed_from_reviews",
                to="procurement.purchaserequest",
            ),
        ),
        migrations.AddField(
            model_name="manualreviewqueue",
            name="resume_error_code",
            field=models.CharField(
                blank=True,
                help_text="resume_status=failed 時的非敏感錯誤代碼；不落地原始例外訊息或供應商名稱",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manualreviewqueue",
            name="resume_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "not_applicable"),
                    ("pending", "pending"),
                    ("succeeded", "succeeded"),
                    ("failed", "failed"),
                ],
                default="not_applicable",
                help_text="supplier_fuzzy_match 案件核准後續傳解析的持久化狀態，可依 failed 重試",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manualreviewqueue",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                db_column="requester_user_id",
                help_text="模糊比對案件：原始詢價發起人，核准後 Django 直接續傳解析時用來建立採購需求草稿",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_review_entries",
                to="core.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualreviewqueue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resume_status", "succeeded"), _negated=True),
                    ("created_purchase_request__isnull", False),
                    _connector="OR",
                ),
                name="manual_review_queue_resume_succeeded_has_purchase_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualreviewqueue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resume_status", "failed"), _negated=True),
                    ("resume_error_code__isnull", False),
                    _connector="OR",
                ),
                name="manual_review_queue_resume_failed_has_error_code",
            ),
        ),
    ]
