# Generated by Django 5.2.17 on 2026-08-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="成本/單價", max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="TWD", max_length=10)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_qty", models.IntegerField(default=0, help_text="目前庫存數量")),
                (
                    "threshold",
                    models.IntegerField(help_text="低於此值觸發 purchase_suggestions"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="erp.product",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="PurchaseSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_qty",
                    models.IntegerField(
                        help_text="系統建議本次補貨數量，演算法於實作階段定案"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processed", "processed"),
                            ("dismissed", "dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_suggestions",
                        to="erp.product",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_suggestions",
            },
        ),
    ]
