# Generated by Django 5.2.17 on 2026-08-28 12:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='產品類別唯一代碼', max_length=50, unique=True)),
                ('name', models.CharField(db_comment='產品類別名稱', max_length=100)),
                ('spec_schema', models.JSONField(db_comment='產品規格驗證定義，必須為 JSON object', default=dict)),
                ('is_active', models.BooleanField(db_comment='是否允許新產品使用此類別', default=True)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'product_categories',
                'db_table_comment': '產品類別與規格定義主檔',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_comment='品項描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_comment='品項是否可用於新交易', default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_comment='企業內部品項代碼', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(db_comment='依產品類別定義驗證的規格值 JSON object', default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(db_comment='計量單位，例如 EA、KG', default='EA', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', db_comment='產品類別；舊資料可暫為 NULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.productcategory'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('sku',), name='products_sku_unique'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE product_categories
                    ADD CONSTRAINT product_categories_schema_object_check
                    CHECK (jsonb_typeof(spec_schema) = 'object');
                ALTER TABLE products
                    ADD CONSTRAINT products_specifications_object_check
                    CHECK (jsonb_typeof(specifications) = 'object');
                CREATE TRIGGER product_categories_set_updated_at
                BEFORE UPDATE ON product_categories
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER products_set_updated_at
                BEFORE UPDATE ON products
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS products_set_updated_at ON products;
                DROP TRIGGER IF EXISTS product_categories_set_updated_at ON product_categories;
                ALTER TABLE products DROP CONSTRAINT IF EXISTS products_specifications_object_check;
                ALTER TABLE product_categories DROP CONSTRAINT IF EXISTS product_categories_schema_object_check;
            """,
        ),
    ]
