# Generated by Django 5.2.17 on 2026-08-29 01:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('erp', '0002_productcategory_product_description_and_more'),
        ('procurement', '0007_awarddecision_approvalcase_awardline_purchaseorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(db_comment='收貨單唯一編號', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('inspecting', 'inspecting'), ('posted', 'posted'), ('partially_accepted', 'partially_accepted'), ('rejected', 'rejected'), ('voided', 'voided')], db_comment='狀態：draft/inspecting/posted/partially_accepted/rejected/voided', default='draft', max_length=30)),
                ('received_at', models.DateTimeField(blank=True, db_comment='實際收貨時間；離開 draft 後必填', null=True)),
                ('version', models.PositiveIntegerField(db_comment='樂觀鎖版本，必須大於 0', default=1)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
                ('legacy_quote', models.OneToOneField(blank=True, db_column='legacy_quote_id', db_comment='舊 quotes.id；僅 legacy migration 使用', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migrated_goods_receipt', to='procurement.quote')),
                ('purchase_order', models.ForeignKey(db_column='purchase_order_id', db_comment='對應 purchase_orders.id', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(db_column='received_by_id', db_comment='實際記錄收貨的 users.id', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_goods_receipts', to='core.user')),
            ],
            options={
                'db_table': 'goods_receipts',
                'db_table_comment': '採購單的分批收貨主檔',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(db_comment='本批實收數量，必須大於 0；跨批累計不得超過訂購量', decimal_places=3, max_digits=14)),
                ('lot_no', models.CharField(blank=True, db_comment='供應商批號或序號群組', max_length=100)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('purchase_order_item', models.ForeignKey(db_column='purchase_order_item_id', db_comment='對應 purchase_order_items.id', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='procurement.purchaseorderitem')),
                ('receipt', models.ForeignKey(db_column='receipt_id', db_comment='對應 goods_receipts.id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.goodsreceipt')),
            ],
            options={
                'db_table': 'goods_receipt_items',
                'db_table_comment': '收貨批次的逐項實收紀錄',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', db_comment='對應 products.id，亦為本表主鍵', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='inventory_balance', serialize=False, to='erp.product')),
                ('on_hand_quantity', models.DecimalField(db_comment='已驗收合格且實際在庫數量', decimal_places=3, default=0, max_digits=14)),
                ('reserved_quantity', models.DecimalField(db_comment='已保留但尚未出庫數量', decimal_places=3, default=0, max_digits=14)),
                ('in_transit_quantity', models.DecimalField(db_comment='已發出採購單但尚未完成驗收數量快照', decimal_places=3, default=0, max_digits=14)),
                ('version', models.PositiveIntegerField(db_comment='樂觀鎖版本，必須大於 0', default=1)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'inventory_balances',
                'db_table_comment': '品項庫存餘額查詢快照；真相來源為 inventory_movements',
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand_quantity__gte', 0), ('reserved_quantity__gte', 0), ('in_transit_quantity__gte', 0)), name='inventory_balances_quantities_nonnegative'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='inventory_balances_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt_accept', 'receipt_accept'), ('return_out', 'return_out'), ('issue_out', 'issue_out'), ('adjustment_in', 'adjustment_in'), ('adjustment_out', 'adjustment_out'), ('reversal', 'reversal'), ('migration_assumed_receipt', 'migration_assumed_receipt')], db_comment='異動類型：receipt_accept/return_out/issue_out/adjustment_in/adjustment_out/reversal/migration_assumed_receipt', max_length=40)),
                ('quantity_delta', models.DecimalField(db_comment='庫存數量增減值，不得為 0', decimal_places=3, max_digits=14)),
                ('reference_type', models.CharField(db_comment='來源類型，例如 quality_inspection', max_length=50)),
                ('reference_id', models.PositiveBigIntegerField(db_comment='來源資料主鍵')),
                ('affects_balance', models.BooleanField(db_comment='是否實際影響 inventory_balances', default=True)),
                ('reason', models.TextField(db_comment='異動或更正原因')),
                ('posted_at', models.DateTimeField(db_comment='正式過帳時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('posted_by', models.ForeignKey(blank=True, db_column='posted_by_id', db_comment='過帳者 users.id；系統 migration 可為 NULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_inventory_movements', to='core.user')),
                ('product', models.ForeignKey(db_column='product_id', db_comment='對應 products.id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='erp.product')),
            ],
            options={
                'db_table': 'inventory_movements',
                'db_table_comment': '不可覆寫的庫存異動流水帳',
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('partially_accepted', 'partially_accepted'), ('rejected', 'rejected')], db_comment='結果：accepted/partially_accepted/rejected', max_length=30)),
                ('accepted_quantity', models.DecimalField(db_comment='合格數量；只有此數量可入庫', decimal_places=3, default=0, max_digits=14)),
                ('defective_quantity', models.DecimalField(db_comment='瑕疵待處理數量；不得入庫', decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(db_comment='直接拒收數量；不得入庫', decimal_places=3, default=0, max_digits=14)),
                ('defect_details', models.TextField(blank=True, db_comment='瑕疵內容；defective_quantity 大於 0 時必填')),
                ('inspected_at', models.DateTimeField(db_comment='品質驗收完成時間')),
                ('notes', models.TextField(blank=True, db_comment='驗收補充說明')),
                ('created_at', models.DateTimeField(db_comment='建立時間（由資料庫產生）', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('inspected_by', models.ForeignKey(db_column='inspected_by_id', db_comment='執行品質驗收的 users.id', on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to='core.user')),
                ('receipt_item', models.OneToOneField(db_column='receipt_item_id', db_comment='對應 goods_receipt_items.id；每筆收貨明細只能有一筆最終驗收', on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspection', to='erp.goodsreceiptitem')),
            ],
            options={
                'db_table': 'quality_inspections',
                'db_table_comment': '收貨明細的最終品質驗收結果',
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='goods_receipts_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('received_at__isnull', True), ('status', 'draft')), models.Q(models.Q(('status', 'draft'), _negated=True), ('received_at__isnull', False)), _connector='OR'), name='goods_receipts_received_time_consistent'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'purchase_order_item'), name='goods_receipt_items_receipt_po_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='goods_receipt_items_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(fields=('reference_type', 'reference_id', 'movement_type'), name='inventory_movements_reference_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_movements_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inventory_movements_reason_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_quantity__gte', 0), ('defective_quantity__gte', 0), ('rejected_quantity__gte', 0)), name='quality_inspections_quantities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.CheckConstraint(condition=models.Q(('defective_quantity', 0), models.Q(models.Q(('defect_details', ''), _negated=True), ('defect_details__isnull', False)), _connector='OR'), name='quality_inspections_defect_details_required'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE goods_receipts ADD CONSTRAINT goods_receipts_status_check
                    CHECK (status IN ('draft', 'inspecting', 'posted', 'partially_accepted', 'rejected', 'voided'));
                ALTER TABLE quality_inspections ADD CONSTRAINT quality_inspections_status_check
                    CHECK (status IN ('accepted', 'partially_accepted', 'rejected'));
                ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_type_check
                    CHECK (movement_type IN (
                        'receipt_accept', 'return_out', 'issue_out', 'adjustment_in',
                        'adjustment_out', 'reversal', 'migration_assumed_receipt'
                    ));
                ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_direction_check
                    CHECK (
                        (movement_type IN ('receipt_accept', 'adjustment_in', 'migration_assumed_receipt')
                            AND quantity_delta > 0)
                        OR (movement_type IN ('return_out', 'issue_out', 'adjustment_out')
                            AND quantity_delta < 0)
                        OR movement_type = 'reversal'
                    );
                ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_migration_balance_check
                    CHECK (movement_type <> 'migration_assumed_receipt' OR affects_balance = false);

                CREATE TRIGGER goods_receipts_set_updated_at BEFORE UPDATE ON goods_receipts
                    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
                CREATE TRIGGER inventory_balances_set_updated_at BEFORE UPDATE ON inventory_balances
                    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();

                CREATE OR REPLACE FUNCTION enforce_goods_receipt_item_quantity()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    receipt_po_id bigint;
                    item_po_id bigint;
                    ordered_qty numeric(14,3);
                    already_received numeric(14,3);
                BEGIN
                    SELECT purchase_order_id INTO receipt_po_id
                    FROM goods_receipts WHERE id = NEW.receipt_id;
                    SELECT purchase_order_id, ordered_quantity
                    INTO item_po_id, ordered_qty
                    FROM purchase_order_items
                    WHERE id = NEW.purchase_order_item_id
                    FOR UPDATE;
                    IF receipt_po_id IS NULL OR item_po_id IS NULL OR receipt_po_id <> item_po_id THEN
                        RAISE EXCEPTION 'receipt item must belong to the receipt purchase order'
                            USING ERRCODE = 'foreign_key_violation';
                    END IF;
                    SELECT COALESCE(SUM(received_quantity), 0)
                    INTO already_received
                    FROM goods_receipt_items
                    WHERE purchase_order_item_id = NEW.purchase_order_item_id
                      AND id <> COALESCE(NEW.id, -1);
                    IF already_received + NEW.received_quantity > ordered_qty THEN
                        RAISE EXCEPTION 'cumulative received quantity exceeds ordered quantity'
                            USING ERRCODE = 'check_violation';
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER goods_receipt_items_quantity_check
                    BEFORE INSERT OR UPDATE OF receipt_id, purchase_order_item_id, received_quantity
                    ON goods_receipt_items
                    FOR EACH ROW EXECUTE FUNCTION enforce_goods_receipt_item_quantity();

                CREATE OR REPLACE FUNCTION enforce_quality_inspection_quantities()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    received_qty numeric(14,3);
                BEGIN
                    SELECT received_quantity INTO received_qty
                    FROM goods_receipt_items WHERE id = NEW.receipt_item_id;
                    IF received_qty IS NULL OR
                       NEW.accepted_quantity + NEW.defective_quantity + NEW.rejected_quantity <> received_qty THEN
                        RAISE EXCEPTION 'inspection quantities must equal received quantity'
                            USING ERRCODE = 'check_violation';
                    END IF;
                    IF (NEW.status = 'accepted' AND
                            (NEW.accepted_quantity <> received_qty OR
                             NEW.defective_quantity <> 0 OR NEW.rejected_quantity <> 0))
                       OR (NEW.status = 'partially_accepted' AND
                            (NEW.accepted_quantity <= 0 OR
                             NEW.defective_quantity + NEW.rejected_quantity <= 0))
                       OR (NEW.status = 'rejected' AND NEW.accepted_quantity <> 0) THEN
                        RAISE EXCEPTION 'inspection status is inconsistent with quantity allocation'
                            USING ERRCODE = 'check_violation';
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER quality_inspections_quantity_check
                    BEFORE INSERT OR UPDATE OF receipt_item_id, status, accepted_quantity,
                        defective_quantity, rejected_quantity
                    ON quality_inspections
                    FOR EACH ROW EXECUTE FUNCTION enforce_quality_inspection_quantities();

                CREATE OR REPLACE FUNCTION protect_inspected_receipt_item()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM quality_inspections WHERE receipt_item_id = OLD.id) THEN
                        RAISE EXCEPTION 'inspected receipt item is immutable'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;
                    RETURN OLD;
                END;
                $$;
                CREATE TRIGGER goods_receipt_items_inspected_immutable
                    BEFORE UPDATE OR DELETE ON goods_receipt_items
                    FOR EACH ROW EXECUTE FUNCTION protect_inspected_receipt_item();

                CREATE OR REPLACE FUNCTION enforce_receipt_accept_movement()
                RETURNS trigger LANGUAGE plpgsql AS $$
                DECLARE
                    inspection_product_id bigint;
                    inspection_accepted_qty numeric(14,3);
                    inspection_status varchar;
                BEGIN
                    IF NEW.movement_type = 'receipt_accept' THEN
                        IF NEW.reference_type <> 'quality_inspection' OR NEW.affects_balance = false THEN
                            RAISE EXCEPTION 'receipt acceptance movement requires an affecting quality inspection reference'
                                USING ERRCODE = 'check_violation';
                        END IF;
                        SELECT poi.product_id, qi.accepted_quantity, qi.status
                        INTO inspection_product_id, inspection_accepted_qty, inspection_status
                        FROM quality_inspections qi
                        JOIN goods_receipt_items gri ON gri.id = qi.receipt_item_id
                        JOIN purchase_order_items poi ON poi.id = gri.purchase_order_item_id
                        WHERE qi.id = NEW.reference_id;
                        IF inspection_product_id IS NULL OR inspection_product_id <> NEW.product_id
                           OR inspection_status NOT IN ('accepted', 'partially_accepted')
                           OR inspection_accepted_qty <= 0
                           OR NEW.quantity_delta <> inspection_accepted_qty THEN
                            RAISE EXCEPTION 'receipt movement must match accepted inspection product and quantity'
                                USING ERRCODE = 'check_violation';
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$;
                CREATE TRIGGER inventory_movements_receipt_check
                    BEFORE INSERT ON inventory_movements
                    FOR EACH ROW EXECUTE FUNCTION enforce_receipt_accept_movement();

                CREATE OR REPLACE FUNCTION prevent_inventory_movement_mutation()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'inventory movements are append-only'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$;
                CREATE TRIGGER inventory_movements_immutable
                    BEFORE UPDATE OR DELETE ON inventory_movements
                    FOR EACH ROW EXECUTE FUNCTION prevent_inventory_movement_mutation();

                CREATE OR REPLACE FUNCTION prevent_quality_inspection_mutation()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'quality inspections are immutable; create a correction record'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$;
                CREATE TRIGGER quality_inspections_immutable
                    BEFORE UPDATE OR DELETE ON quality_inspections
                    FOR EACH ROW EXECUTE FUNCTION prevent_quality_inspection_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS quality_inspections_immutable ON quality_inspections;
                DROP FUNCTION IF EXISTS prevent_quality_inspection_mutation();
                DROP TRIGGER IF EXISTS inventory_movements_immutable ON inventory_movements;
                DROP FUNCTION IF EXISTS prevent_inventory_movement_mutation();
                DROP TRIGGER IF EXISTS inventory_movements_receipt_check ON inventory_movements;
                DROP FUNCTION IF EXISTS enforce_receipt_accept_movement();
                DROP TRIGGER IF EXISTS goods_receipt_items_inspected_immutable ON goods_receipt_items;
                DROP FUNCTION IF EXISTS protect_inspected_receipt_item();
                DROP TRIGGER IF EXISTS quality_inspections_quantity_check ON quality_inspections;
                DROP FUNCTION IF EXISTS enforce_quality_inspection_quantities();
                DROP TRIGGER IF EXISTS goods_receipt_items_quantity_check ON goods_receipt_items;
                DROP FUNCTION IF EXISTS enforce_goods_receipt_item_quantity();
                DROP TRIGGER IF EXISTS inventory_balances_set_updated_at ON inventory_balances;
                DROP TRIGGER IF EXISTS goods_receipts_set_updated_at ON goods_receipts;
                ALTER TABLE inventory_movements DROP CONSTRAINT IF EXISTS inventory_movements_migration_balance_check;
                ALTER TABLE inventory_movements DROP CONSTRAINT IF EXISTS inventory_movements_direction_check;
                ALTER TABLE inventory_movements DROP CONSTRAINT IF EXISTS inventory_movements_type_check;
                ALTER TABLE quality_inspections DROP CONSTRAINT IF EXISTS quality_inspections_status_check;
                ALTER TABLE goods_receipts DROP CONSTRAINT IF EXISTS goods_receipts_status_check;
            """,
        ),
    ]
