# Generated by Django 5.2.17 on 2026-08-30 07:01

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


FORWARD_SQL = r"""
ALTER TABLE purchase_suggestions ADD CONSTRAINT purchase_suggestions_status_check
    CHECK (status IN ('pending', 'in_progress', 'processed', 'dismissed'));
ALTER TABLE inspection_variance_cases ADD CONSTRAINT inspection_variance_cases_status_check
    CHECK (status IN ('draft', 'open', 'closed', 'cancelled'));
ALTER TABLE inspection_variance_lines ADD CONSTRAINT inspection_variance_lines_action_check
    CHECK (action_type IN ('replacement', 'return', 'credit', 'waive'));
ALTER TABLE inspection_variance_lines ADD CONSTRAINT inspection_variance_lines_status_check
    CHECK (status IN ('pending', 'completed', 'cancelled'));

CREATE TRIGGER inspection_variance_cases_set_updated_at
    BEFORE UPDATE ON inspection_variance_cases
    FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();

CREATE OR REPLACE FUNCTION enforce_inspection_variance_case()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    variance_qty numeric(14,3);
    allocated_qty numeric(14,3);
BEGIN
    SELECT defective_quantity + rejected_quantity INTO variance_qty
    FROM quality_inspections WHERE id = NEW.quality_inspection_id;
    IF variance_qty IS NULL OR variance_qty <= 0 THEN
        RAISE EXCEPTION 'variance case requires defective or rejected quantity'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.status IN ('open', 'closed') THEN
        SELECT COALESCE(SUM(quantity), 0) INTO allocated_qty
        FROM inspection_variance_lines
        WHERE variance_case_id = NEW.id AND status <> 'cancelled';
        IF allocated_qty <> variance_qty THEN
            RAISE EXCEPTION 'active variance line quantities must equal inspection variance quantity'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.submitted_by_id IS NULL OR NEW.submitted_at IS NULL THEN
            RAISE EXCEPTION 'submitted actor and time are required for open variance case'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.status = 'closed' AND (NEW.closed_by_id IS NULL OR NEW.closed_at IS NULL) THEN
        RAISE EXCEPTION 'closed actor and time are required for closed variance case'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER inspection_variance_case_check
    AFTER INSERT OR UPDATE ON inspection_variance_cases
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION enforce_inspection_variance_case();

CREATE OR REPLACE FUNCTION protect_submitted_variance_lines()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    case_status varchar;
BEGIN
    SELECT status INTO case_status FROM inspection_variance_cases
    WHERE id = COALESCE(NEW.variance_case_id, OLD.variance_case_id);
    IF case_status <> 'draft' THEN
        RAISE EXCEPTION 'submitted variance lines are immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER inspection_variance_lines_immutable
    BEFORE UPDATE OR DELETE ON inspection_variance_lines
    FOR EACH ROW EXECUTE FUNCTION protect_submitted_variance_lines();

CREATE OR REPLACE FUNCTION enforce_goods_receipt_item_quantity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    receipt_po_id bigint;
    item_po_id bigint;
    ordered_qty numeric(14,3);
    already_received numeric(14,3);
    replacement_qty numeric(14,3);
    replacement_po_item_id bigint;
    replacement_action varchar;
    replacement_case_status varchar;
BEGIN
    SELECT purchase_order_id INTO receipt_po_id FROM goods_receipts WHERE id = NEW.receipt_id;
    SELECT purchase_order_id, ordered_quantity INTO item_po_id, ordered_qty
    FROM purchase_order_items WHERE id = NEW.purchase_order_item_id FOR UPDATE;
    IF receipt_po_id IS NULL OR item_po_id IS NULL OR receipt_po_id <> item_po_id THEN
        RAISE EXCEPTION 'receipt item must belong to the receipt purchase order'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    IF NEW.replacement_variance_line_id IS NULL THEN
        SELECT COALESCE(SUM(received_quantity), 0) INTO already_received
        FROM goods_receipt_items
        WHERE purchase_order_item_id = NEW.purchase_order_item_id
          AND replacement_variance_line_id IS NULL
          AND id <> COALESCE(NEW.id, -1);
        IF already_received + NEW.received_quantity > ordered_qty THEN
            RAISE EXCEPTION 'cumulative original received quantity exceeds ordered quantity'
                USING ERRCODE = 'check_violation';
        END IF;
    ELSE
        SELECT ivl.quantity, gri.purchase_order_item_id, ivl.action_type, ivc.status
        INTO replacement_qty, replacement_po_item_id, replacement_action, replacement_case_status
        FROM inspection_variance_lines ivl
        JOIN inspection_variance_cases ivc ON ivc.id = ivl.variance_case_id
        JOIN quality_inspections qi ON qi.id = ivc.quality_inspection_id
        JOIN goods_receipt_items gri ON gri.id = qi.receipt_item_id
        WHERE ivl.id = NEW.replacement_variance_line_id;
        IF replacement_action <> 'replacement' OR replacement_case_status NOT IN ('open', 'closed')
           OR replacement_po_item_id <> NEW.purchase_order_item_id THEN
            RAISE EXCEPTION 'replacement receipt requires an active matching replacement line'
                USING ERRCODE = 'check_violation';
        END IF;
        SELECT COALESCE(SUM(received_quantity), 0) INTO already_received
        FROM goods_receipt_items
        WHERE replacement_variance_line_id = NEW.replacement_variance_line_id
          AND id <> COALESCE(NEW.id, -1);
        IF already_received + NEW.received_quantity > replacement_qty THEN
            RAISE EXCEPTION 'cumulative replacement received quantity exceeds authorized quantity'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

COMMENT ON TABLE inspection_variance_cases IS '品質驗收差異的後續處理案件';
COMMENT ON TABLE inspection_variance_lines IS '驗收差異的退貨、補交、折讓或短交結案拆量明細';
COMMENT ON COLUMN inspection_variance_cases.id IS '驗收差異案件主鍵';
COMMENT ON COLUMN inspection_variance_cases.quality_inspection_id IS '對應 quality_inspections.id';
COMMENT ON COLUMN inspection_variance_cases.status IS 'draft/open/closed/cancelled';
COMMENT ON COLUMN inspection_variance_cases.version IS '樂觀鎖版本';
COMMENT ON COLUMN inspection_variance_cases.created_by_id IS '建立案件的 users.id';
COMMENT ON COLUMN inspection_variance_cases.submitted_by_id IS '正式提出處理方案的 users.id';
COMMENT ON COLUMN inspection_variance_cases.submitted_at IS '正式提出處理方案時間';
COMMENT ON COLUMN inspection_variance_cases.closed_by_id IS '結案者 users.id';
COMMENT ON COLUMN inspection_variance_cases.closed_at IS '正式結案時間';
COMMENT ON COLUMN inspection_variance_cases.created_at IS '建立時間';
COMMENT ON COLUMN inspection_variance_cases.updated_at IS '最後更新時間，由 trigger 維護';
COMMENT ON COLUMN inspection_variance_lines.id IS '驗收差異處理明細主鍵';
COMMENT ON COLUMN inspection_variance_lines.variance_case_id IS '對應 inspection_variance_cases.id';
COMMENT ON COLUMN inspection_variance_lines.action_type IS 'replacement/return/credit/waive';
COMMENT ON COLUMN inspection_variance_lines.status IS 'pending/completed/cancelled';
COMMENT ON COLUMN inspection_variance_lines.quantity IS '本處理方式涵蓋的差異數量';
COMMENT ON COLUMN inspection_variance_lines.reason IS '處理理由';
COMMENT ON COLUMN inspection_variance_lines.completed_by_id IS '完成處理的 users.id';
COMMENT ON COLUMN inspection_variance_lines.completed_at IS '完成處理時間';
COMMENT ON COLUMN inspection_variance_lines.created_at IS '建立時間';
COMMENT ON COLUMN goods_receipt_items.replacement_variance_line_id IS '補交收貨依據的 inspection_variance_lines.id';
COMMENT ON COLUMN purchase_suggestions.source_movement_id IS '觸發建議的 inventory_movements.id';
COMMENT ON COLUMN purchase_suggestions.purchase_request_id IS '由建議轉成的 purchase_requests.id';
COMMENT ON COLUMN purchase_suggestions.suggested_qty IS '補足目標庫存所需建議數量';
COMMENT ON COLUMN purchase_suggestions.status IS 'pending/in_progress/processed/dismissed';
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS inspection_variance_lines_immutable ON inspection_variance_lines;
DROP FUNCTION IF EXISTS protect_submitted_variance_lines();
DROP TRIGGER IF EXISTS inspection_variance_case_check ON inspection_variance_cases;
DROP FUNCTION IF EXISTS enforce_inspection_variance_case();
DROP TRIGGER IF EXISTS inspection_variance_cases_set_updated_at ON inspection_variance_cases;
ALTER TABLE purchase_suggestions DROP CONSTRAINT IF EXISTS purchase_suggestions_status_check;
CREATE OR REPLACE FUNCTION enforce_goods_receipt_item_quantity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    receipt_po_id bigint;
    item_po_id bigint;
    ordered_qty numeric(14,3);
    already_received numeric(14,3);
BEGIN
    SELECT purchase_order_id INTO receipt_po_id FROM goods_receipts WHERE id = NEW.receipt_id;
    SELECT purchase_order_id, ordered_quantity INTO item_po_id, ordered_qty
    FROM purchase_order_items WHERE id = NEW.purchase_order_item_id FOR UPDATE;
    IF receipt_po_id IS NULL OR item_po_id IS NULL OR receipt_po_id <> item_po_id THEN
        RAISE EXCEPTION 'receipt item must belong to the receipt purchase order'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    SELECT COALESCE(SUM(received_quantity), 0) INTO already_received
    FROM goods_receipt_items
    WHERE purchase_order_item_id = NEW.purchase_order_item_id
      AND id <> COALESCE(NEW.id, -1);
    IF already_received + NEW.received_quantity > ordered_qty THEN
        RAISE EXCEPTION 'cumulative received quantity exceeds ordered quantity'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_rolepermission_userrole'),
        ('erp', '0004_legacy_receipt_actor_exception'),
        ('procurement', '0011_purchase_request_rejected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesuggestion',
            name='purchase_request',
            field=models.ForeignKey(blank=True, db_column='purchase_request_id', db_comment='由本建議轉成的採購需求', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_purchase_suggestions', to='procurement.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='source_movement',
            field=models.ForeignKey(blank=True, db_column='source_movement_id', db_comment='觸發建議的庫存流水；既有建議可為 NULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_suggestions', to='erp.inventorymovement'),
        ),
        migrations.AlterField(
            model_name='purchasesuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('processed', 'processed'), ('dismissed', 'dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasesuggestion',
            name='suggested_qty',
            field=models.DecimalField(decimal_places=3, help_text='補足目標庫存所需的建議數量', max_digits=14),
        ),
        migrations.CreateModel(
            name='InspectionVarianceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(db_comment='樂觀鎖版本，必須大於 0', default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_comment='由資料庫 trigger 維護', db_default=django.db.models.functions.datetime.Now())),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_inspection_variances', to='core.user')),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_variances', to='core.user')),
                ('quality_inspection', models.OneToOneField(db_column='quality_inspection_id', db_comment='對應有瑕疵或拒收數量的品質驗收', on_delete=django.db.models.deletion.PROTECT, related_name='variance_case', to='erp.qualityinspection')),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_inspection_variances', to='core.user')),
            ],
            options={
                'db_table': 'inspection_variance_cases',
                'db_table_comment': '品質驗收差異的後續處理案件',
            },
        ),
        migrations.CreateModel(
            name='InspectionVarianceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('replacement', 'replacement'), ('return', 'return'), ('credit', 'credit'), ('waive', 'waive')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('completed_by', models.ForeignKey(blank=True, db_column='completed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_inspection_variance_lines', to='core.user')),
                ('variance_case', models.ForeignKey(db_column='variance_case_id', on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.inspectionvariancecase')),
            ],
            options={
                'db_table': 'inspection_variance_lines',
                'db_table_comment': '驗收差異的拆量處理明細',
            },
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='replacement_variance_line',
            field=models.ForeignKey(blank=True, db_column='replacement_variance_line_id', db_comment='補交收貨所依據的驗收差異明細；一般收貨為 NULL', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_receipt_items', to='erp.inspectionvarianceline'),
        ),
        migrations.AddConstraint(
            model_name='inspectionvariancecase',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='inspection_variance_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='inspectionvarianceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inspection_variance_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inspectionvarianceline',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inspection_variance_line_reason_not_blank'),
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
