# Generated by Django 5.2.17 on 2026-08-28 12:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, db_comment='企業內部供應商代碼', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.JSONField(db_comment='聯絡資料 JSON object；API 依權限遮罩', default=dict),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(db_comment='是否允許用於新交易', default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, db_comment='預設付款條件', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('on_hold', 'on_hold'), ('blocked', 'blocked')], db_comment='供應商狀態：active/on_hold/blocked', default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, db_comment='統一編號或稅籍識別碼', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(db_comment='最後更新時間（由資料庫 trigger 維護）', db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code',), name='suppliers_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__isnull', False)), fields=('tax_id',), name='suppliers_tax_id_unique'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE suppliers
                    ADD CONSTRAINT suppliers_contact_object_check
                    CHECK (jsonb_typeof(contact) = 'object');
                ALTER TABLE suppliers
                    ADD CONSTRAINT suppliers_status_check
                    CHECK (status IN ('active', 'on_hold', 'blocked'));
                CREATE TRIGGER suppliers_set_updated_at
                BEFORE UPDATE ON suppliers
                FOR EACH ROW EXECUTE FUNCTION set_row_updated_at();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS suppliers_set_updated_at ON suppliers;
                ALTER TABLE suppliers DROP CONSTRAINT IF EXISTS suppliers_status_check;
                ALTER TABLE suppliers DROP CONSTRAINT IF EXISTS suppliers_contact_object_check;
            """,
        ),
    ]
